### ISSUE TITLE
Can't "install" the addon

### ISSUE THREAD

**Issue by WarGreySama** [Pherakki/Blender-Tools-for-DSCS#2]
I've been using Blender for 6 years now. So I know my way around it quiet well, as you can imagine. However addon refuses to help I've tried with 4 different versions. Just doesn't work in my main 2.83 LTS - which has bunch of other addons, doesn't even work in other clean installs. 

Tried with 2.80: Clean install, tried installing addon both manually and through Add-on tab, doesn't work 
Tried with 2.90: Same as above 
Tried with 2.91 and 2.92: Same as above
Tried with 2.83: Current daily driver, has a lot of IO addons, did both clean manual installation and clean installation through Blender itself, doesn't work. 

You know when you install an addon and it automatically prompts you into enabling it, that doesn't happen and addon doesn't appear in the list, I've checked dedicated Blender forums and other 3D modelling forums to see what's up but it seems it's not the Blender but the addon itself. Thanks for your hard work (I've been ripping DSCS models from PS4 version, but some models would come out as corrupt thus I've stopped ripping from that version for months now).

**Comment by Pherakki** [comment]
I think this is an issue with the way the package is arranged if you clone the repository. There are two ways you can resolve this:
1. Unpack the zip, and create a zip from a folder with all the repository code contained
e.g. the zip starts off looking like
```
-BlenderIO
-CollatedData
-CustomException
-etc.
```
you should repackage it to look like
```
-some_folder_name
    |-BlenderIO
    |-CollatedData
    |-CustomExceptions
2. Alternatively, you can follow the procedure described in point 2 of the section of the README ["Potential Fixes for Common Bugs"](https://github.com/Pherakki/Blender-Tools-for-DSCS#potential-fixes-for-common-bugs).

Hope that resolves the issue - whenever I make releases, I ensure that the package structure is correct, but I'm holding out until I've fixed some issues with the skeletons and written an animation exporter before the next release.

**Comment by WarGreySama** [comment]
Thanks a lot. An hour after I sent that, it dawned on me that that sometimes happen with repository stuff and I exactly did that. Forgot to report back because I was finally able to rip NXes and some characters I couldn't rip. I mostly ripped stuff from PS4 version though. Sorry about forgetting to report back, issue is solved. Keep up the good work!

**Comment by Pherakki** [comment]
Thanks for confirming. I'm also aware of your model-ripping history judging by your username; so please keep up the good work too ;)
